### ISSUE TITLE
Make a posthtml plugin

### ISSUE THREAD

**Issue by stevenvachon** [quarterto/postcss-remove-unused#5]
[posthtml](https://npmjs.com/posthtml)

Similar plugins:
* [email-remove-unused-css](https://npmjs.com/email-remove-unused-css)
* [posthtml-uglify](https://npmsj.com/posthtml-uglify)

**Comment by apaleslimghost** [comment]
Hi @stevenvachon, thanks for the suggestion! How are you imagining this will work? Rewrite it so it uses the posthtml AST instead of cheerio? I can't see a way of doing that that doesn't require consumers to use both postcss and posthtml, and I think that's too much of a barrier to entry. Also, since it's not actually altering the HTML, just querying it, seems like posthtml is largely unnecessary.

**Comment by stevenvachon** [comment]
Check out [cssnano](https://npmjs.com/cssnano) and [htmlnano](https://npmjs.com/htmlnano) for ideas on providing both plugin and abstracted APIs.

Also, why not alter the HTML? If a class is no longer used, references to it on elements should be removed. Such could be optional, as to avoid issues with selector queries.

The major benefit to this being a plugin is that we can include it as part of a compile/transform chain, without redundant HTML string parsing.

**Comment by stevenvachon** [comment]
Also, why not alter the HTML? If a class is no longer used, references to it on elements should be removed. Such could be optional, as to avoid issues with selector queries.

**Comment by apaleslimghost** [comment]
I think you're misunderstanding what this plugin does 🙂 it removes rules from the CSS that have no references in the HTML. So "If a class is no longer used, references to it on elements should be removed" doesn't make sense, because there *are* no references.

I agree that parsing HTML ourselves is redundant, but postcss-remove-unused is already "part of a compile/transform chain", i.e. the CSS one.

**Comment by stevenvachon** [comment]
Oops, sorry. I'm thinking too much in terms of the many things my app is doing.

And, yeah, what you're saying makes sense. I guess what I'm looking for is something that's part of the posthtml chain rather than postcss chain.
